#pragma config(Sensor, in1,    control,        sensorPotentiometer)
#pragma config(Sensor, in2,    button,         sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool reverseDirection = false;
int power = 0;

int controlToPow(){
	int value = SensorValue(control);
	return (value / 4095.0) * 127;
}

int max(int one, int two){
	if(abs(one) >= abs(two)){
		return one;
	} else {
		return two;
	}
}

void setPower(int power){
	motor[port1] = power;
	motor[port2] = power;
	motor[port3] = power;
	motor[port4] = power;
	motor[port5] = power;
	motor[port6] = power;
	motor[port7] = power;
	motor[port8] = power;
	motor[port9] = power;
	motor[port10] = power;
}

void inputVexnet(){
	power = max(vexRT(Ch3), vexRT(Ch2));
	setPower(power);
}

void updateDirection(){
	if(SensorValue(button) == 0){
		reverseDirection = !reverseDirection;
		wait10Msec(5);
	}
}

void inputControl(){
	updateDirection();
	power = controlToPow();
	if(reverseDirection){
		power = -power;
	}
	//string test = "";
	//sprintf(test, "%i", controlToPow());
	//writeDebugStreamLine(test);
	setPower(power);
}

task main()
{

	while(true){
		inputControl();
	}
}
